---
abstract: 'produce aoa from tree'
author:
  - 'Terrence Brannon'
build_requires:
  Class::MOP: 0
  HTML::Element: 0
  HTML::Element::Library: 0
  Test::Kit: 0
  Test::More: 0
  Test::XML: 0
  XML::Element: 0
  t::lib::My::Shopping: 0
  t::lib::T: 0
  t::lib::U: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200012, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-Writer-Compiler
requires:
  Carp: 0
  Data::Diver: 0
  Data::Dumper: 0
  File::Path: 0
  File::Spec: 0
  Moose: 0
  Moose::Role: 0
  Perl::Tidy: 0
  XML::TreeBuilder: 0
  XML::Writer: 0
  XML::Writer::String: 0
  autodie: 0
version: 1.112060
